/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_trej_regex_Regex */

#ifndef _Included_com_trej_regex_Regex
#define _Included_com_trej_regex_Regex
#ifdef __cplusplus
extern "C" {
#endif
#undef com_trej_regex_Regex_serialVersionUID
#define com_trej_regex_Regex_serialVersionUID -2801431994164874288i64
#undef com_trej_regex_Regex_REG_OK
#define com_trej_regex_Regex_REG_OK 0L
#undef com_trej_regex_Regex_REG_EXTENDED
#define com_trej_regex_Regex_REG_EXTENDED 1L
#undef com_trej_regex_Regex_REG_ICASE
#define com_trej_regex_Regex_REG_ICASE 2L
#undef com_trej_regex_Regex_REG_NEWLINE
#define com_trej_regex_Regex_REG_NEWLINE 4L
#undef com_trej_regex_Regex_REG_NOSUB
#define com_trej_regex_Regex_REG_NOSUB 8L
#undef com_trej_regex_Regex_REG_LITERAL
#define com_trej_regex_Regex_REG_LITERAL 16L
#undef com_trej_regex_Regex_REG_RIGHT_ASSOC
#define com_trej_regex_Regex_REG_RIGHT_ASSOC 32L
#undef com_trej_regex_Regex_REG_UNGREEDY
#define com_trej_regex_Regex_REG_UNGREEDY 64L
/*
 * Class:     com_trej_regex_Regex
 * Method:    match
 * Signature: ()Lcom/trej/regex/MatchResult;
 */
JNIEXPORT jobject JNICALL Java_com_trej_regex_Regex_match
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
